services:
  # Next.js App
  app:
    container_name: guacamole-nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        NODE_ENV: production

    image: guacamole-nextjs-app:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
